#!/bin/bash

[ -e /config/logs/ ] || mkdir /config/logs

while true; do
  [ -e /config/workspace/api/ ] && {
    . /var/venv/bin/activate >> /config/logs/api.script.log 2>&1
    cd /config/workspace/api >> /config/logs/api.script.log 2>&1
    pip install -e ".[dev]" >> /config/logs/api.script.log 2>&1
    uvicorn rdp.api.main:app --reload --host 0.0.0.0 --root-path /api --proxy-headers >> /config/logs/api.run.log 2>&1
    sleep 1
  }
done

