FROM docker.io/library/debian:bookworm-slim 
# FROM docker.io/library/ubuntu:latest
RUN apt-get update && apt-get upgrade -y && \
  apt-get install -y libfuse3-dev cmake gcc g++ libcriterion-dev inotify-tools libfuse3-3 && \ 
  echo All Done
